--- 
## Config file for nf_wochenende and Haybaler
# If you mess up this file, use an online yaml validator to find the problematic lines.

# path to R
rscript_bin: /usr/bin/Rscript
# Servers configured for heat tree analysis with the R and the metacoder R package. String with all server hostnames separated by space: "server1 server2 server3 ..."
heattree_server: "hpc-rc11"
# Path to conda.sh file. eg. /mnt/ngsnfs/tools/miniconda3/etc/profile.d/conda.sh
CONDA_SH_PATH: /mnt/ngsnfs/tools/miniconda3/etc/profile.d/conda.sh
WOCHENENDE_CONDA_ENV_NAME: wochenende
HAYBALER_CONDA_ENV_NAME: haybaler
# Activate multiqc
USE_MULTIQC: "no"
# Adapter sequence locations
adapter_fastp_general: /mnt/ngsnfs/seqres/contaminants/2020_02/adapters/adapters.fa
adapter_fastp_nextera: /mnt/ngsnfs/seqres/contaminants/2020_02/adapters/NexteraPE-PE.fa
adapter_nextera: /mnt/ngsnfs/seqres/contaminants/2020_02/adapters/NexteraPE-PE.fa
#adapter_truseq: /mnt/ngsnfs/tools/miniconda3/envs/wochenende/share/trimmomatic-0.39-2/adapters/TruSeq3-PE.fa
adapter_truseq: /home/hpc/davenpor/programs/miniconda3/envs/wochenende/share/trimmomatic-0.39-2/adapters/TruSeq2-PE.fa
ea_adapter_fasta: /mnt/ngsnfs/seqres/contaminants/2020_02/adapters/adapters.fa
# Paths to tools
#path_abra_jar: /mnt/ngsnfs/tools/abra2/abra2_latest.jar
path_bamtools: bamtools
path_bwa: bwa
path_fastp: fastp
path_fastq_mcf: fastq_mcf
path_fastqc: fastqc
path_fastuniq: fastuniq
path_java: java
path_minimap2: minimap2
path_ngmlr: ngmlr
path_perl: perl
path_perldup: remove_pcr_duplicates.pl
path_prinseq: prinseq-lite.pl
path_sambamba: sambamba
path_samtools: samtools
path_tmpdir: temp
path_trim_galore: trim_galore
path_trimmomatic: trimmomatic
