--- 
## Config file for nf_wochenende and Haybaler
# If you mess up this file, use an online yaml validator to find the problematic lines.

# For paths to program directories - see setup.sh

# set number of threads used in your nextflow.config
#THREADS: 12
# path to R
rscript_bin: /usr/bin/Rscript
# Servers configured for heat tree analysis with the metacoder R package. String with all server hostnames separated by space: "server1 server2 server3 ..."
heattree_server: "hpc-bc15-07 hpc-bc15-12 hpc06 hpc-rc11"
# Path to conda.sh file. eg. /mnt/ngsnfs/tools/miniconda3/etc/profile.d/conda.sh
CONDA_SH_PATH: /home/rcug_lw/miniconda3/etc/profile.d/conda.sh
WOCHENENDE_CONDA_ENV_NAME: wochenende
HAYBALER_CONDA_ENV_NAME: haybaler
# Activate multiqc
USE_MULTIQC: "no"
# Adapter sequence locations
adapter_fastp_general: /mnt/ngsnfs/seqres/metagenref/bwa/Wochenende_reference/adapters/adapters.fa
adapter_fastp_nextera: /mnt/ngsnfs/seqres/metagenref/bwa/Wochenende_reference/adapters/NexteraPE-PE.fa
adapter_fastp_solid: /mnt/ngsnfs/seqres/metagenref/bwa/Wochenende_reference/adapters/adapters_solid.fa
adapter_nextera: /mnt/ngsnfs/seqres/metagenref/bwa/Wochenende_reference/adapters/NexteraPE-PE.fa
#adapter_truseq: /mnt/ngsnfs/tools/miniconda3/envs/wochenende/share/trimmomatic-0.39-2/adapters/TruSeq3-PE.fa
adapter_truseq: /home/rcug_lw/miniconda3/envs/wochenende/share/trimmomatic-0.39-2/adapters/TruSeq2-PE.fa
ea_adapter_fasta: /mnt/ngsnfs/seqres/metagenref/bwa/Wochenende_reference/adapters/adapters.fa
# Paths to tools
#path_abra_jar: /mnt/ngsnfs/tools/abra2/abra2_latest.jar
#path_afterqc: /mnt/ngsnfs/tools/afterQC/AfterQC-0.9.6/after.py
#path_alignerboost: /mnt/ngsnfs/tools/dev/Wochenende/dependencies/AlignerBoost.jar
path_bamtools: bamtools
path_bwa: bwa
path_fastp: fastp
path_fastq_mcf: fastq_mcf
path_fastqc: fastqc
path_fastuniq: fastuniq
path_java: java
path_minimap2: minimap2
path_ngmlr: ngmlr
path_perl: perl
path_perldup: /mnt/ngsnfs/rcug_lw/lisa/nf_wochenende/dependencies/remove_pcr_duplicates.pl
path_prinseq: prinseq-lite.pl
path_sambamba: sambamba
path_samtools: samtools
path_tmpdir: temp
path_trim_galore: trim_galore
path_trimmomatic: trimmomatic
# Reference sequences for Wochenende
#path_refseq_dict: 
#  2019_01_meta: /mnt/ngsnfs/seqres/metagenref/bwa/all_kingdoms_refseq_2019_Jan_final.fasta
#  2019_01_meta_mouse: /mnt/ngsnfs/seqres/metagenref/bwa/all_kingdoms_refseq_2019_Jan_final_mm10_no_human.fasta
#  2019_01_meta_mouse_ASF: /mnt/ngsnfs/seqres/metagenref/bwa/mm10_plus_ASF.fasta
#  2019_01_meta_mouse_ASF_OMM: /mnt/ngsnfs/seqres/metagenref/bwa/mm10_plus_ASF_OMM.fasta
#  2019_01_meta_mouse_OMM: /mnt/ngsnfs/seqres/metagenref/bwa/mm10_plus_OMM.fasta
#  2021_07_meta_fungi_mouse_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_07_mouse_bact_fungi_vir.fa 
#  2021_11_meta_fungi_mouse_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_11_mouse_bact_arch_fungi_vir.fa 
#  2019_10_meta_human: /mnt/ngsnfs/seqres/metagenref/bwa/refSeqs_allKingdoms_201910_3.fasta
#  2019_10_meta_human_univec: /mnt/ngsnfs/seqres/metagenref/bwa/refSeqs_allKingdoms_201910_3_with_UniVec.fasta
#  2020_03_meta_human: /mnt/ngsnfs/seqres/metagenref/bwa/refSeqs_allKingdoms_2020_03.fa
#  2020_05_meta_human: /mnt/ngsnfs/seqres/metagenref/bwa/refSeqs_allKingdoms_2020_05.fa
#  2020_09_massiveref_human: /mnt/ngsnfs/seqres/metagenref/bwa/2020_09_massiveref.fa
#  2021_02_meta_fungi_human_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_02_human_bact_fungi_vir_masked.fa
#  2021_02_meta_fungi_human_unmasked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_02_human_bact_fungi_vir_unmasked.fa
#  2021_08_meta_fungi_human_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_08_human_bact_arch_fungi_vir.fa
#  2021_09_meta_fungi_human_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_09_human_bact_arch_fungi_vir.fa
#  2021_10_meta_fungi_human_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_10_human_bact_arch_fungi_vir.fa
#  2021_12_meta_fungi_human_masked: /mnt/ngsnfs/seqres/metagenref/bwa/2021_12_human_bact_arch_fungi_vir.fa
#  GRCh37: /mnt/ngsnfs/seqres/HS/bwa/GRCh37.fa
#  GRCh38-45GB: /mnt/ngsnfs/seqres/HS/bwa/Homo_sapiens.GRCh38.dna.toplevel.fa
#  GRCh38-mito: /mnt/ngsnfs/seqres/HS/bwa/Homo_sapiens.GRCh38.dna.chromosome.MT.fa
#  GRCh38-noalt: /mnt/ngsnfs/seqres/HS/bwa/GRCh38_no_alt.fa
#  T2T_v1_1: /mnt/ngsnfs/seqres/HS/bwa/chm13.draft_v1.1_plus_Y.fasta
#  seqins_v3: /mnt/ngsnfs/seqres/metagenref/bwa/metasequin_sequences_3.0.fa
#  2021_12_meta_fungi_human_masked_seqins_v3: /mnt/ngsnfs/seqres/metagenref/bwa/2021_12_human_bact_arch_fungi_vir_metasequins.fa
#  PA14: /mnt/ngsnfs/seqres/PA/bwa/NC_008463.fna
#  citro_freundii: /mnt/ngsnfs/seqres/metagenref/bwa/citro_freundii.fa
#  clost_bot: /mnt/ngsnfs/seqres/metagenref/bwa/clost_bot.fa
#  clost_bot_e: /mnt/ngsnfs/seqres/metagenref/bwa/clost_bot_e_contigs.fa
#  clost_diff: /mnt/ngsnfs/seqres/metagenref/bwa/clost_diff.fa
#  clost_perf: /mnt/ngsnfs/seqres/metagenref/bwa/clost_perf.fa
#  ecoli: /mnt/ngsnfs/seqres/EC/bwa/ecoli_K_12_MG1655.fasta
#  ezv_viruses: /mnt/ngsnfs/seqres/metagenref/bwa/EZV0_1_database2_cln.fasta
#  hg19: /mnt/ngsnfs/seqres/HS/bwa/hg19.fa
#  k_oxytoca: /mnt/ngsnfs/seqres/metagenref/bwa/k_oxytoca.fa
#  k_variicola: /mnt/ngsnfs/seqres/metagenref/bwa/k_variicola.fa
#  mm10: /mnt/ngsnfs/seqres/MM/bwa/mm10.fa
#  GRCm39: /mnt/ngsnfs/seqres/MM/Mus_musculus.GRCm39.dna.toplevel.fa
#  nci_viruses: /mnt/ngsnfs/seqres/metagenref/bwa/nci_viruses.fa
#  rat_1AR1_ont: /mnt/ngsnfs/seqres/RN/bwa/1AR1_2019_ONT_final.fasta
#  rn6: /mnt/ngsnfs/seqres/RN/bwa/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa
#  ss11: /mnt/ngsnfs/seqres/SS/bwa/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa
#  ssplasmid1: /mnt/ngsnfs/seqres/plasmids/bwa/pX330_NLS1_2-AKCP204LgRneoR_cln.fasta
#  ssplasmid2: /mnt/ngsnfs/seqres/plasmids/bwa/SB-U6-gRNA-eCas9-DNLS1_2-EGFP-Neo_cln.fasta
#  strept_halo: /mnt/ngsnfs/seqres/metagenref/bwa/strept_halo.fa
#  testdb: /mnt/ngsnfs/rcug_lw/lisa/nf_wochenende/test/data/ref.fa
#  zf10: /mnt/ngsnfs/seqres/DR/bwa/GRCz10.fa
